# Generated by Django 5.2.7 on 2025-10-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMonth',
            fields=[
                ('expense_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_months', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
