# Generated by Django 5.2.7 on 2025-12-06 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('expense_budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('expense_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('expense_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('fk_budget_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensebudget')),
                ('fk_payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensepayment')),
                ('fk_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='expensebudget',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'budget'), name='unique_user_expense_budget'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'payment'), name='unique_user_expense_payment'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'type'), name='unique_user_expense_type'),
        ),
    ]
