# Generated by Django 5.2.7 on 2025-10-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemonth',
            old_name='fk_user',
            new_name='fk_user_id',
        ),
    ]
