# Generated by Django 5.2.7 on 2025-10-12 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_fk_user_expensemonth_fk_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensemonth',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'date'), name='unique_user_month'),
        ),
    ]
