# Generated by Django 5.2.7 on 2025-10-12 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensemonth_unique_user_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemonth',
            old_name='expense_record_id',
            new_name='expense_month_id',
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('expense_budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('expense_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('expense_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
