# Generated by Django 5.2.7 on 2025-10-12 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_expense_record_id_expensemonth_expense_month_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensebudget',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'budget'), name='unique_user_expense_budget'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'payment'), name='unique_user_expense_payment'),
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(fields=('fk_user_id', 'type'), name='unique_user_expense_type'),
        ),
    ]
