# Generated by Django 5.2.7 on 2025-10-12 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fk_budget_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensebudget'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fk_expense_month_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensemonth'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fk_payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensepayment'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fk_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensetype'),
        ),
    ]
